revised/blog-after/config/routes.rb
Blog::Application.routes.draw do
  resources :articles do
    resources :comments
  end
  
  resources :photos do
    resources :comments
  end
  
  resources :events do
    resources :comments
  end
  
  root to: 'articles#index'
end

revised/blog-after/app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :name
  has_many :comments, as: :commentable
end

revised/blog-after/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :commentable, polymorphic: true
end

revised/blog-after/app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :ends_at, :name, :starts_at
  has_many :comments, as: :commentable
end

revised/blog-after/app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :filename, :name
  has_many :comments, as: :commentable
end

revised/blog-after/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

revised/blog-after/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @commentable = @article
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url, notice: "Article was destroyed."
  end
end

revised/blog-after/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable
  
  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.new(params[:comment])
    if @comment.save
      redirect_to @commentable, notice: "Comment created."
    else
      render :new
    end
  end

private

  def load_commentable
    resource, id = request.path.split('/')[1, 2]
    @commentable = resource.singularize.classify.constantize.find(id)
  end

  # def load_commentable
  #   klass = [Article, Photo, Event].detect { |c| params["#{c.name.underscore}_id"] }
  #   @commentable = klass.find(params["#{klass.name.underscore}_id"])
  # end
end

revised/blog-after/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to @event, notice: "Event was successfully created."
    else
      render :new
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: "Event was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, notice: "Event was destroyed."
  end
end

revised/blog-after/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      redirect_to @photo, notice: "Photo was successfully created."
    else
      render :new
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(params[:photo])
      redirect_to @photo, notice: "Photo was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url, notice: "Photo was destroyed."
  end
end

revised/blog-after/app/helpers/application_helper.rb
module ApplicationHelper
end

revised/blog-after/app/helpers/articles_helper.rb
module ArticlesHelper
end

revised/blog-after/app/helpers/comments_helper.rb
module CommentsHelper
end

revised/blog-after/app/helpers/events_helper.rb
module EventsHelper
end

revised/blog-after/app/helpers/photos_helper.rb
module PhotosHelper
end

revised/blog-after/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revised/blog-after/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

revised/blog-after/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
<% @articles.each do |article| %>
  <h2><%= link_to article.name, article %></h2>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>
<p><%= link_to "New Article", new_article_path %></p>

revised/blog-after/app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

revised/blog-after/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>

<%= simple_format @article.content %>

<p><%= link_to "Back to Articles", articles_path %></p>

<h2>Comments</h2>

<%= render "comments/comments" %>
<%= render "comments/form" %>

revised/blog-after/app/views/comments/_comments.html.erb
<div id="comments">
<% @comments.each do |comment| %>
  <div class="comment">
    <%= simple_format comment.content %>
  </div>
<% end %>
</div>

revised/blog-after/app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revised/blog-after/app/views/comments/index.html.erb
<h1>Comments</h1>

<%= render 'comments' %>


<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>

revised/blog-after/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

revised/blog-after/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

revised/blog-after/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

revised/blog-after/app/views/events/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
  <div class="event">
    <h3><%= event.name %></h3>
    <div class="date">From <%= event.starts_at.strftime("%B %d, %Y") %> to <%= event.ends_at.strftime("%B %d, %Y") %></div>
    <div><%= event.description %></div>
  </div>
<% end %>

<p><%= link_to "New Event", new_event_path %></p>

revised/blog-after/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

revised/blog-after/app/views/events/show.html.erb
<h1>Event</h1>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Starts at:</b>
  <%= @event.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @event.ends_at %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

revised/blog-after/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <div id="nav">
        <%= link_to_unless_current "Articles", articles_path %> |
        <%= link_to_unless_current "Photos", photos_path %> |
        <%= link_to_unless_current "Events", events_path %>
      </div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>